cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/media/psf/iCloud/Uni/Masterthesis/ss20-ma-kaywallasshek-ml-mptcp/ns3-mptcp/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/media/psf/iCloud/Uni/Masterthesis/ss20-ma-kaywallasshek-ml-mptcp/ns3-mptcp/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 140283695022608: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-std=c++11\', \'-march=native\', \'-DHAVE___UINT128_T=1\', \'-DINT64X64_USE_128=1\', \'-DHAVE_SYS_TYPES_H=1\', \'-DHAVE_SYS_STAT_H=1\', \'-DHAVE_DIRENT_H=1\', \'-DHAVE_STDLIB_H=1\', \'-DHAVE_GETENV=1\', \'-DHAVE_SIGNAL_H=1\', \'-DHAVE_PTHREAD_H=1\', \'-DHAVE_STDINT_H=1\', \'-DHAVE_INTTYPES_H=1\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
